let S = {
    "testA": [
        ["Shrek", "some text"],
        ["Shrek", "some more text"],
        ["Shrek", "some more interesting text"],
        ["Onion", "According to all known laws of aviation,"],
        ["Onion", "there is no way that a bee should be able to fly."],
        ["Onion", "Its wings are too small to get its fat little body off the ground."],
        ["Onion", "The bee, of course, flies anyways."],
        ["Shrek", "Because bees don't care what humans think is impossible."],
        ["Onion", "Haha, what a story, Mark."],
        ["Shrek", "MY SWAMP?"],
    ],
    "testB": [
        ["Shrek", "e"],
        ["Nagito", "e"],
        ["Shrek", "e"],
        ["Onion", "e"],
        ["Shrek", "e"],
        ["Onion", "e"],
        ["Shrek", "e"],
        ["Onion", "e"],
        ["Shrek", "e"],
        ["Onion", "e"],
        ["Shrek", "e"],
        ["Onion", "e"],
    ],
    "testC": [
        ["*p", "u up?", 0],
        ["*p", "i wanna talk", 0],
        ["Onion", "what is it", 60],
        ["*p", "tell me about ur kind", 0],
        ["Onion", "The onion, also known as the bulb onion or common onion,", 120],
        ["Onion", "is a vegetable that is the", 60],
        ["Onion", "most widely cultivated species of the genus Allium.", 120],
        ["Onion", "The shallot is a botanical variety of the onion", 120],
        ["Onion", "which was classified as a separate species", 120],
        ["Onion", "until 2010.", 40],
        ["Onion", "Its close relatives include garlic,", 240],
        ["*p", "scallion,", 0],
        ["Onion", "leek,", 120],
        ["Nagito", "and chive.", 60],
        ["Onion", "w h a t", 100],
        ["*p", "last text", 0],
    ],
    "momMorningOne":[
        ["Mom","Hi Honey! Are you ready for your first day of work?"],
        ["Player","I'm [nervous/anxious/worried]"],
        ["Mom","Afraid you'll fall in love? You know I want grandbabies, so that wouldn't be too bad ;)"],
        ["Mom","What for? You've always been a killer with women, men, and more. I'm sure you'll do fine and maybe bring home some grandbabies ;)"],
        ["Mom","There's no need to worry, all the people you flirt with will be sure to have someone to show them a good time, and there's no way they'll know it was you. Wish it was you so I could get some grandbabies ;)        "],
        ["Player","Okay mom. I've gotta go ttyl."],
        ["Mom","Break some hearts!! <3 <3"],
    ],
    "BFFMorningOne":[
        ["BFF","Hey Hey, ready for the first day? Still not 100% sure what you do at that job."],
        ["Player","As far as I know, I set up dates, to not go on them."],
        ["BFF","To *not* go on them?"],
        ["Player","To NOT go on them…"],
        ["BFF","I still don't get it, but if it pays rent it pays rent. Beats farming that's for sure."],
        ["BFF","Don't think I haven't noticed you dodging my question."],
        ["Player","I'm [Ready/Not Ready]"],
        ["BFF","Good to hear. Well I hope it goes well. Don't fall in love haha."],
        ["Player","Not planning on it…"],
        ["BFF","Ready: I'm sure you'll do fine. And hey, that rent isn't gonna earn itself. So get out there and give 'em the goods, big shooter"],
        ["Player","Great encouragement as always."],
    ],
}